- name: Get ssh credentials
  delegate_to: localhost
  ansible.builtin.set_fact:
    ansible_user: "{{ devicecreds.username }}"
    ansible_password: "{{ devicecreds.password }}"
    ansible_connection: "network_cli"
    ansible_network_cli_ssh_type: "paramiko"
    ansible_network_os: community.ciscosmb.ciscosmb
  listen: Push config
  no_log: true

- name: Push new config and reload
  community.ciscosmb.command:
    commands:
      - scp://{{ scpuser.username }}:{{ scpuser.password }}@{{ controller_ip }}/{{ hostvars[inventory_hostname]['sites'][0] }}/{{ inventory_hostname }}.conf
      - reload
