- name: Pull rendered configs from API
  delegate_to: localhost
  ansible.builtin.uri:
    method: "POST"
    url: "{{ netbox_api }}/api/dcim/devices/{{ hostvars[inventory_hostname]['device_id'] }}/render-config/"
    headers:
      Authorization: "Token {{ netbox_token }}"
  register: config

- name: Get credentials from passbolt
  delegate_to: localhost
  ansible.builtin.set_fact:
    pbresult: "{{ lookup(passbolt, inventory_hostname) }}"
  environment:
    PASSBOLT_BASE_URL: "{{ passbolt_url }}"
    PASSBOLT_PRIVATE_KEY: "{{ passbolt_pkey }}"
    PASSBOLT_PASSPHRASE: "{{ passbolt_pass }}"
  no_log: true

- name: Put template into file
  delegate_to: localhost
  ansible.builtin.template:
    mode: "0644"
    src: "prePassTemplates/{{ hostvars[inventory_hostname]['sites'][0] }}/{{ inventory_hostname }}.j2"
    dest: "configs/{{ hostvars[inventory_hostname]['sites'][0] }}/{{ inventory_hostname }}.conf"
  notify:
    - Push config
  no_log: true

- name: Trigger Push config
  delegate_to: localhost
  ansible.builtin.command: /bin/true
  changed_when: true
  notify: Push config
